In [54]:
import numpy as np
import trimesh

mesh = trimesh.load("sample_meshes/Sample_Crimp_8.stl")

# print(mesh.triangles[1])

intersection_mesh = trimesh.ray.ray_triangle.RayMeshIntersector(mesh)

ray_origin = np.array([[17.1, 3, 34], [0, 0, 34]])
ray_dir = np.array([[0, 0, -1], [0, 0, -1]])

print(ray_origin)
print(ray_dir)

bruh_test = intersection_mesh.intersects_first(ray_origin, ray_dir)
print(bruh_test)

print(mesh.triangles[bruh_test[0]])
print(mesh.triangles[bruh_test[1]])

bruh_test_2 = intersection_mesh.intersects_location(ray_origin, ray_dir)
print(f"bruh_test_2:{bruh_test_2}")

locations = bruh_test_2[0]
ray_indices = bruh_test_2[1]

for i in range(2):
    dawg = ray_indices == i
    masked_locations = locations[dawg]
    print(masked_locations)
    masked_locations = masked_locations[:,2]
    print(masked_locations)
    print(np.max(masked_locations))

[[17.1  3.  34. ]
 [ 0.   0.  34. ]]
[[ 0  0 -1]
 [ 0  0 -1]]
[2016 2478]
[[17.1769352   3.7265532  10.57978535]
 [16.50645447  2.66030216 10.7142601 ]
 [17.6311245   2.87585616  9.9950552 ]]
[[-0.98197579 -0.05329224 19.2277317 ]
 [ 0.13217457 -0.37833396 18.66819382]
 [-0.11270414  0.35742801 19.25520897]]
bruh_test_2:(array([[0.00000000e+00, 0.00000000e+00, 7.10542736e-15],
       [0.00000000e+00, 0.00000000e+00, 1.89719081e+01],
       [1.71000000e+01, 3.00000000e+00, 7.10542736e-15],
       [1.71000000e+01, 3.00000000e+00, 1.04056036e+01]]), array([1, 1, 0, 0]), array([ 824, 2478,  797, 2016]))
[[1.71000000e+01 3.00000000e+00 7.10542736e-15]
 [1.71000000e+01 3.00000000e+00 1.04056036e+01]]
[7.10542736e-15 1.04056036e+01]
10.40560357340076
[[0.00000000e+00 0.00000000e+00 7.10542736e-15]
 [0.00000000e+00 0.00000000e+00 1.89719081e+01]]
[7.10542736e-15 1.89719081e+01]
18.971908147654403


In [ ]:
import numpy as np
import trimesh

ray_origins = []
ray_directions = []

for i in range(201):
    for j in range(201):
        ray_origins.append([i, j, np.inf])
        ray_directions.append([0, 0, -1])

mesh = trimesh.load("sample_meshes/Sample_Crimp_8.stl")
intersection_mesh = trimesh.ray.ray_triangle.RayMeshIntersector(mesh)

intersections = intersection_mesh.intersects_location(np.array(ray_origins), np.array(ray_directions))

locations = intersections[0]
ray_indices = intersections[1]

max = -np.inf
max_pts = []
for i in range(ray_origins.shape[0]):
    ray_index = ray_indices == i
    masked_locations = locations[ray_index]
    max = -np.inf
    max_pt = []
    for location in masked_locations:
        if (location[2] > max):
            max = location[2]
            max_pt = location
    max_pts.append(max_pt)


        

/home/gabez/miniconda3/envs/tangen/lib/python3.11/site-packages/trimesh/ray/ray_triangle.py:390: RuntimeWarning: invalid value encountered in multiply
  on_a = (ray_directions * t_a) + ray_origins
/home/gabez/miniconda3/envs/tangen/lib/python3.11/site-packages/trimesh/ray/ray_triangle.py:390: RuntimeWarning: invalid value encountered in add
  on_a = (ray_directions * t_a) + ray_origins
/home/gabez/miniconda3/envs/tangen/lib/python3.11/site-packages/trimesh/ray/ray_triangle.py:391: RuntimeWarning: invalid value encountered in multiply
  on_b = (ray_directions * t_b) + ray_origins
/home/gabez/miniconda3/envs/tangen/lib/python3.11/site-packages/trimesh/ray/ray_triangle.py:391: RuntimeWarning: invalid value encountered in add
  on_b = (ray_directions * t_b) + ray_origins


RTreeError: Coordinates must not have minimums more than maximums